version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - "7000"
    env_file:
      - ./server/.env
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
       - VITE_API_BASE_URL=/
    ports:
      - "5173:80"
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
